### ISSUE TITLE
How to add annotation or overlay to the map?

### ISSUE THREAD

**Issue by steve21124** [RossAnderson/EarthView#5]
I would like to add pulse/mark annotation for 5 second and disappear. is it possible?

**Comment by RossAnderson** [comment]
Of course, anything is possible. Presumably you would want to implement your annotation as a CALayer, so you would need a way to place, follow, and occlude that layer when "pinned" to the 3D map. You can use the built-in methods to convert a lat/long to a pixel onscreen and test for occlusion for a given camera viewpoint. Then generate a controller class that updates the layer any time the camera viewpoint changes. It would take the lat/long, convert to pixel, and check for occlusion. The. It would set the location of the layer, and hide it if occluded. The layer would then follow the Earth as if it were pinned down. 

The implementation is left as an exercise to the reader.

**Comment by steve21124** [comment]
:). Thanks, Good tips. I ended using other globe library
